ui: tape
browsers:
  - name: firefox
    version: 28..latest
    platform: Windows 7
  - name: chrome
    version: latest
  - name: ie
    version: 8..latest
  - name: iphone
    version: latest
  - name: android
    version: latest
